export const FEEDBACK_COPY = {
  actions: {
    ok: 'Done',
    cancel: 'Cancel',
    continue: 'Next',
    startNew: 'Start New',
    notNow: 'Not now',
    delete: 'Delete',
    uploadScorecard: 'Add Scorecard',
    addManually: 'Add Manually',
    assignCourse: 'Assign Course',
    saveAnyway: 'Save Anyway',
    restorePurchase: 'Restore Purchase',
    upgradeToPro: 'See full stat tracking',
    pleaseWait: 'Working',
    saveAndContinue: 'Save and Next',
    yesEnterThem: "Yes, I'll enter them",
    noDontHaveThem: "No, I don't have them",
  },
  alerts: {
    compareLimitTitle: 'Compare limit',
    compareLimitBody: 'Select up to 4 rounds to compare.',
    noOpportunitiesTitle: 'No opportunities recorded',
    noOpportunitiesBody: 'No attempts here yet.',
    noHolesSavedTitle: 'No Holes Saved',
    noHolesSavedBody: 'Tap "Save Hole" on at least one hole to save your round.',
    copiedTitle: 'Copied',
    copiedBody: 'Scorecard HTML copied to clipboard.',
    shareRoundTitle: 'Share Round',
    shareRoundBody: 'Choose a share card size.',
    editOnWebTitle: 'Edit on Web',
    editOnWebBody: 'Scorecard editing is available on web.',
    invalidRatingTitle: 'Invalid Rating',
    invalidRatingBody: 'Enter valid course details.',
    invalidSlopeTitle: 'Invalid Slope',
    courseSelectedTitle: 'Course Selected',
    courseSelectedBody: 'This course is missing tee data.',
    courseLookupFailedTitle: 'Course lookup failed',
    courseLookupFailedBody: 'Could not find that course. Try again.',
    homeCourseTitle: 'Home Course',
    homeCourseUpdateFailedBody: 'Could not update your home course. Try again.',
    offlineModeTitle: 'Offline Mode',
    offlineCourseSearchBody: 'Course search requires an internet connection.',
    offlineNearbyBody: 'Finding nearby courses requires an internet connection.',
    resumeRoundTitle: 'Resume Round?',
    errorLoadingCourseTitle: 'Error Loading Course',
    errorLoadingCourseBody: 'Could not load the course. Try again or add it manually.',
    courseNotInDatabaseTitle: 'Course Not in Database',
    requiredTitle: 'Required',
    requiredCourseNameBody: 'Enter the course name.',
    requiredCityStateBody: 'Enter city and state.',
    requiredTeeNameBody: 'Enter the tee name, like White Tees.',
    courseSavedTitle: 'Course Saved',
    courseSavedNoHandicapBody: 'This round will be saved for history and stats, but not used for player rating.',
    invalidRatingRangeBody: 'Course difficulty value is out of range.',
    invalidSlopeRangeBody: 'Course slope value is out of range.',
    golfSumProUnlockedTitle: 'Pro is active',
    golfSumProUnlockedBody: 'Your subscription is active.',
    purchaseNotCompletedTitle: 'Purchase not completed',
    purchaseNotCompletedBody: 'No changes were made.',
    purchaseRestoredTitle: 'Purchase restored',
    purchaseRestoredBody: 'Pro is active on this account.',
    nothingToRestoreTitle: 'Nothing to restore',
    nothingToRestoreBody: 'No active Pro subscription was found.',
    cameraNotAvailableTitle: 'Camera not available',
    cameraNotAvailableBody: 'Use Select from Photos on web.',
    cameraAccessNeededTitle: 'Camera access needed',
    cameraAccessNeededBody: 'Allow camera access to take a scorecard photo.',
    ocrFinishedTitle: 'OCR Finished',
    ocrFinishedNoStructuredDataBody: 'We could read the image, but not the hole details. Fill in the fields manually.',
    ocrSlowTitle: 'OCR Taking Longer Than Expected',
    ocrSlowBody: 'This image is taking longer to process. Try again in a moment or use a smaller image.',
    ocrFailedTitle: 'OCR Failed',
    ocrFailedFallbackBody: 'Could not read this scorecard. Fill in the fields manually.',
    locationNeededTitle: 'Location Needed',
    locationEnableBody: 'Turn on location services to find nearby courses.',
    locationEnterCityStateBody: 'Enter a city and state to search nearby courses.',
    missingCourseNameTitle: 'Missing Course Name',
    missingCourseNameBody: 'Enter a course name.',
    missingTeeBoxesTitle: 'Missing Tee Boxes',
    missingTeeBoxesBody: 'Add at least one tee box.',
    invalidTeeDataTitle: 'Invalid Tee Data',
    invalidTeeDataBody: 'Check the tee details.',
    saveFailedTitle: 'Save Failed',
    saveCourseFailedBody: 'Could not save this course. Try again.',
    saveRoundFailedBody: 'Could not save this round. Try again.',
    importUnavailableTitle: 'Import Unavailable',
    importUnavailableBody: 'Round import is not configured.',
    assignCourseTitle: 'Assign Course?',
    assignCourseBody: 'Would you like to assign a course to this round before saving?',
    missingScoresTitle: 'Missing Scores',
    missingScoresBody: 'Enter at least 9 hole scores to import a round.',
    incompleteScoresTitle: 'Incomplete Scores',
    incompleteScores18Body: 'Enter all 18 hole scores, or only the front 9, to import a completed round.',
    incompleteScores9Body: 'Enter all 9 hole scores to import a completed round.',
    importCompleteTitle: 'Import Complete',
    importCompleteBody: '1 round imported. Your averages are ready.',
  },
  modals: {
    deleteRoundTitle: 'Delete Round?',
    deleteRoundWarning: 'This action cannot be undone.',
    deleteRoundFromHistoryBody: 'This will remove the round from your history.',
  },
} as const;
