export const FEEDBACK_COPY = {
  actions: {
    ok: 'OK',
    cancel: 'Cancel',
    continue: 'Continue',
    startNew: 'Start New',
    notNow: 'Not now',
    delete: 'Delete',
    uploadScorecard: 'Upload Scorecard',
    addManually: 'Add Manually',
    assignCourse: 'Assign Course',
    saveAnyway: 'Save Anyway',
    restorePurchase: 'Restore Purchase',
    upgradeToPro: 'Upgrade to Pro',
    pleaseWait: 'Please wait...',
    saveAndContinue: 'Save & Continue',
    yesEnterThem: "Yes, I'll enter them",
    noDontHaveThem: "No, I don't have them",
  },
  alerts: {
    compareLimitTitle: 'Compare limit',
    compareLimitBody: 'Select up to 4 rounds to compare.',
    noOpportunitiesTitle: 'No opportunities recorded',
    noOpportunitiesBody: 'You have not recorded any attempts yet.',
    noHolesSavedTitle: 'No Holes Saved',
    noHolesSavedBody: 'Tap "Save Hole" on at least one hole to save your round.',
    copiedTitle: 'Copied',
    copiedBody: 'Scorecard HTML copied to clipboard.',
    shareRoundTitle: 'Share Round',
    shareRoundBody: 'Choose a share card size.',
    editOnWebTitle: 'Edit on Web',
    editOnWebBody: 'Scorecard editing is available on web.',
    invalidRatingTitle: 'Invalid Rating',
    invalidRatingBody: 'Enter valid course details.',
    invalidSlopeTitle: 'Invalid Slope',
    courseSelectedTitle: 'Course Selected',
    courseSelectedBody: 'This course is missing tee data.',
    courseLookupFailedTitle: 'Course lookup failed',
    courseLookupFailedBody: 'Please try again.',
    homeCourseTitle: 'Home Course',
    homeCourseUpdateFailedBody: 'Unable to update home course right now. Please try again.',
    offlineModeTitle: 'Offline Mode',
    offlineCourseSearchBody: 'Course search requires an internet connection.',
    offlineNearbyBody: 'Finding nearby courses requires an internet connection.',
    resumeRoundTitle: 'Resume Round?',
    errorLoadingCourseTitle: 'Error Loading Course',
    errorLoadingCourseBody: 'Unable to fetch course details. Please try again or add the course manually.',
    courseNotInDatabaseTitle: 'Course Not in Database',
    requiredTitle: 'Required',
    requiredCourseNameBody: 'Please enter the course name',
    requiredCityStateBody: 'Please enter city and state',
    requiredTeeNameBody: 'Please enter the tee name (e.g., "White Tees")',
    courseSavedTitle: 'Course Saved',
    courseSavedNoHandicapBody: 'This round will be saved for history and stats, but not used for player rating.',
    invalidRatingRangeBody: 'Course difficulty value is out of range.',
    invalidSlopeRangeBody: 'Course slope value is out of range.',
    golfSumProUnlockedTitle: 'GolfSum Pro unlocked',
    golfSumProUnlockedBody: 'Your subscription is active.',
    purchaseNotCompletedTitle: 'Purchase not completed',
    purchaseNotCompletedBody: 'No changes were made.',
    purchaseRestoredTitle: 'Purchase restored',
    purchaseRestoredBody: 'GolfSum Pro is active on this account.',
    nothingToRestoreTitle: 'Nothing to restore',
    nothingToRestoreBody: 'No active Pro subscription was found.',
    cameraNotAvailableTitle: 'Camera not available',
    cameraNotAvailableBody: 'Use Select from Photos on web.',
    cameraAccessNeededTitle: 'Camera access needed',
    cameraAccessNeededBody: 'Please allow camera access to take a scorecard photo.',
    ocrFinishedTitle: 'OCR Finished',
    ocrFinishedNoStructuredDataBody: 'We could read the image but could not detect structured hole data. Please fill in the fields manually.',
    ocrSlowTitle: 'OCR Taking Longer Than Expected',
    ocrSlowBody: 'The OCR server is still processing this image. Please try again in a moment or use a smaller image.',
    ocrFailedTitle: 'OCR Failed',
    ocrFailedFallbackBody: 'We could not read this scorecard. Please fill in the fields manually.',
    locationNeededTitle: 'Location Needed',
    locationEnableBody: 'Enable location services to find nearby courses.',
    locationEnterCityStateBody: 'Enter a city and state to search nearby courses.',
    missingCourseNameTitle: 'Missing Course Name',
    missingCourseNameBody: 'Please enter a course name.',
    missingTeeBoxesTitle: 'Missing Tee Boxes',
    missingTeeBoxesBody: 'Please add at least one tee box.',
    invalidTeeDataTitle: 'Invalid Tee Data',
    invalidTeeDataBody: 'Please check tee details.',
    saveFailedTitle: 'Save Failed',
    saveCourseFailedBody: 'Could not save this course. Please try again.',
    saveRoundFailedBody: 'Could not save this round. Please try again.',
    importUnavailableTitle: 'Import Unavailable',
    importUnavailableBody: 'Round import is not configured.',
    assignCourseTitle: 'Assign Course?',
    assignCourseBody: 'Would you like to assign a course to this round before saving?',
    missingScoresTitle: 'Missing Scores',
    missingScoresBody: 'Please enter at least 9 hole scores to import a round.',
    incompleteScoresTitle: 'Incomplete Scores',
    incompleteScores18Body: 'Please enter all 18 hole scores (or only the front 9) to import a completed round.',
    incompleteScores9Body: 'Please enter all 9 hole scores to import a completed round.',
    importCompleteTitle: 'Import Complete',
    importCompleteBody: '1 round imported. Your averages are ready.',
  },
  modals: {
    deleteRoundTitle: 'Delete Round?',
    deleteRoundWarning: 'This action cannot be undone.',
    deleteRoundFromHistoryBody: 'This will remove the round from your history.',
  },
} as const;
