export const UI_COPY = {
  actions: {
    startRound: 'Start a Round',
    startNewRound: 'Start a New Round',
    trackRound: 'Track a Round',
    trackNextRound: 'Track Next Round',
    importScorecard: 'Import a Scorecard',
    importScorecards: 'Import Scorecards',
  },
  labels: {
    noDataYet: 'No stats here yet.',
  },
  manualCourseEntry: {
    headerTitle: 'Add Custom Course',
    infoBanner: "Can't find your course? Add it here.",
    sectionTitle: 'Course Information',
    courseNameLabel: 'Course Name *',
    cityLabel: 'City *',
    stateLabel: 'State *',
    teeNameLabel: 'Tee Name *',
    courseNamePlaceholder: 'e.g., Pine Valley Golf Club',
    cityPlaceholder: 'e.g., Phoenix',
    statePlaceholder: 'e.g., AZ',
    teeNamePlaceholder: 'e.g., White Tees, Blue Tees',
    privateCourse: 'Private Course',
    whsTitle: 'GolfSum Rating',
    whsBody: 'This course is not in our database yet. You can still save rounds and build your GolfSum Player Rating from score vs par.',
    continue: 'Next',
    ratingTitle: 'Course Details',
    ratingPrompt: 'Save this custom course for future rounds?',
    ratingHint: 'GolfSum Player Rating uses your score vs par and does not require course rating/slope.',
    enterRatingTitle: 'Course Details',
    courseRatingLabel: 'Course Difficulty',
    slopeRatingLabel: 'Course Slope',
    courseRatingPlaceholder: 'e.g., 71.2',
    slopeRatingPlaceholder: 'e.g., 125',
    courseRatingRange: 'Range: 60.0 - 80.0',
    slopeRatingRange: 'Range: 55 - 155',
    disclaimer: 'GolfSum Player Rating is based on your score vs par.',
  },
  scorecardImport: {
    titleImportCompleted: 'Import Scorecard',
    titleUpload: 'Add Scorecard',
    reviewRoundTitle: 'Review Round',
    unknownCourse: 'Unknown course',
    teeFallback: 'Tee',
    dateFallback: 'Date',
    reviewCardTitle: 'Review Round',
    reviewCardBody: 'Check the scores and yardages. Tap any cell to fix it.',
    importedNotesWithPlayer: 'Imported scorecard ({playerName})',
    importedNotesDefault: 'Imported scorecard',
    sectionTabPhoto: 'Photo',
    sectionTabStats: 'Stats',
    sectionTabCourse: 'Course',
    sectionTabYardage: 'Yardage',
    scanScoresAndStats: 'Scores & stats',
    scanBackSideScores: 'Back side scores',
    scanCourseAndTees: 'Course & tees',
    scanYardagesAndPars: 'Yardages & pars',
    scanDetailPartialReview: 'Partial - review needed',
    scanDetailNotDetectedManual: 'Not detected - add manually',
    stickyNext: 'Next',
    stickySaveRound: 'Save Round',
    stickySaveCourseAndStart: 'Save Course and Start Round',
    unknownTeeName: 'Unknown',
    unknownCourseSaveOverride: 'Unknown Course',
    handicapIncompleteScores: 'Incomplete: missing scores',
    handicapNotEligibleCourse: 'Not eligible: course missing',
    handicapNotEligibleTee: 'Not eligible: tee missing',
    handicapNotEligibleRatingSlope: 'Unrated: course details missing',
    keypadTitleFallback: 'Value',
    keypadTitleScore: 'Score',
    keypadTitlePutts: 'Putts',
    keypadTitlePenalties: 'Penalties',
    keypadTitleFairway: 'Fairway',
    keypadTitleGreen: 'Green in Regulation',
    keypadTitlePar: 'Par',
    keypadTitleHcpMen: 'Hole Allowance (Men)',
    keypadTitleHcpWomen: 'Hole Allowance (Women)',
    keypadTitleYardage: 'Yardage',
    keypadTitleRatingMen: 'Men Course Difficulty',
    keypadTitleSlopeMen: 'Men Course Slope',
    keypadTitleRatingWomen: 'Women Course Difficulty',
    keypadTitleSlopeWomen: 'Women Course Slope',
    keypadChooseValue: 'Choose value',
    holeLabelPrefix: 'Hole',
    reviewStatusComplete: 'Complete',
    reviewStatusNeedsReview: 'Needs review',
    reviewChipDateNotSet: 'not set',
    reviewChipDateFallback: 'Date',
    datePickerTitle: 'Select Date',
    datePickerDone: 'Done',
    photoSectionTitle: 'Scorecard Photo',
    photoPlaceholder: 'Scorecard Photo',
    photoShowsLabel: 'CARD SHOWS',
    playedFullLabel: 'ROUND LENGTH',
    all18Holes: 'All 18 holes',
    yesAddOtherNine: 'Add the other 9',
    noNineHoleRound: '9-hole round',
    addBackCardPrompt: 'Add the Back 9 card',
    addFrontCardPrompt: 'Add the Front 9 card',
    front9: 'Front 9',
    back9: 'Back 9',
    roundLength: 'Round length',
    holes18: '18 Holes',
    holes9: '9 Holes',
    actionSelectFromPhotos: 'Choose Photo',
    actionTakePhoto: 'Take Photo',
    actionSelectBackPhoto: 'Choose Back Photo',
    actionChangePhoto: 'Choose New Photo',
    actionSelectAnotherPhoto: 'Choose Another Photo',
    actionScanScorecard: 'Read Scorecard',
    progressExtracting: 'Reading scorecard {progress}%',
    stepsAfterSelectingPhoto: 'Next',
    stepsReadyToExtract: 'Ready to scan',
    stepsExtracting: 'Reading scorecard',
    stepsExtractionComplete: 'Scan complete',
    stepsExtractionCompleteWarnings: 'Scan complete with notes',
    stepsExtractionFailed: 'Extraction failed',
    scanErrorTitle: 'Could not read scorecard',
    scanErrorTry: 'Try this',
    scanErrorBulletLighting: 'Better lighting',
    scanErrorBulletFlatten: 'Flatten the card',
    scanErrorBulletCrop: 'Crop to the scorecard',
    retryScan: 'Retry Scan',
    enterManually: 'Add Manually',
    twoSidedOrNineTitle: '18 holes or 9 holes',
    twoSidedOrNineBody: '{holes} holes found. Add the other side for all 18, or mark this as a 9-hole round.',
    actionSelectPhoto: 'Select Photo',
    statusFrontScanned: 'Front scanned',
    statusBackScanned: 'Back scanned',
    reviewInStatsTab: 'Review Stats',
    courseDetailsTitle: 'Course Details',
    ratingMissingTitle: 'Course details missing',
    ratingMissingSubtitle: 'Add par and tee details for this course.',
    addRating: 'Add details',
    courseNamePlaceholderShort: 'Course name',
    findNearby: 'Nearby',
    findingNearby: 'Finding nearby',
    searchHint: 'Search by name or pick a nearby course.',
    cityPlaceholderShort: 'City',
    statePlaceholderShort: 'State',
    countryPlaceholder: 'Country (US)',
    roundLengthTitle: 'Round Length',
    teeBoxesTitle: 'Tee Boxes',
    addTee: 'Add Tee',
    teeBoxNamePlaceholder: 'Tee box name',
    removeTee: 'Remove Tee',
    menRating: 'Men Rating',
    menSlope: 'Men Slope',
    womenRating: 'Women Rating',
    womenSlope: 'Women Slope',
    yardagesParTitle: 'Yardages & Par',
    front9Title: 'Front 9',
    back9Title: 'Back 9',
    yardageHeaderPar: 'Par',
    yardageHeaderHcp: 'HCP',
    yardageHeaderYds: 'Yds',
    yardageOut: 'OUT:',
    yardageIn: 'IN:',
    yardageParPrefix: 'Par {par}',
    yardageYdsSuffix: '• {yds} yds',
    playerStatsTitle: 'Player Stats',
    playerStatsTapToCorrect: 'Tap a value to fix it',
    playerNamePlaceholder: 'Player name',
    chooseNameFromScorecard: 'Pick name from card',
    headerScr: 'Scr',
    headerPtt: 'Ptt',
    headerPen: 'Pen',
    upgradeEditAdvanced: 'Add fairways, greens, scrambling, and penalties here',
    trackAdvancedWithPro: 'Add fairways, greens, and miss trends here',
    showAllStats: 'Show more stats',
    puttsSuffix: '• {putts} putts',
  },
} as const;
