export const UI_COPY = {
  actions: {
    startRound: 'Start a Round',
    startNewRound: 'Start a New Round',
    trackRound: 'Track a Round',
    trackNextRound: 'Track Next Round',
    importScorecard: 'Import a Scorecard',
    importScorecards: 'Import Scorecards',
  },
  labels: {
    noDataYet: 'No data yet.',
  },
  manualCourseEntry: {
    headerTitle: 'Add Custom Course',
    infoBanner: "Can't find your course in our database? Enter it manually below.",
    sectionTitle: 'Course Information',
    courseNameLabel: 'Course Name *',
    cityLabel: 'City *',
    stateLabel: 'State *',
    teeNameLabel: 'Tee Name *',
    courseNamePlaceholder: 'e.g., Pine Valley Golf Club',
    cityPlaceholder: 'e.g., Phoenix',
    statePlaceholder: 'e.g., AZ',
    teeNamePlaceholder: 'e.g., White Tees, Blue Tees',
    privateCourse: 'Private Course',
    whsTitle: 'GolfSum Rating',
    whsBody: "This course is not in our database. You can still save rounds and build your GolfSum Player Rating from score vs par.",
    continue: 'Continue',
    ratingTitle: 'Course Details',
    ratingPrompt: 'Save this custom course for future rounds?',
    ratingHint: 'GolfSum Player Rating uses your score vs par and does not require course rating/slope.',
    enterRatingTitle: 'Course Details',
    courseRatingLabel: 'Course Difficulty',
    slopeRatingLabel: 'Course Slope',
    courseRatingPlaceholder: 'e.g., 71.2',
    slopeRatingPlaceholder: 'e.g., 125',
    courseRatingRange: 'Range: 60.0 - 80.0',
    slopeRatingRange: 'Range: 55 - 155',
    disclaimer: 'GolfSum Player Rating is based on your score vs par.',
  },
  scorecardImport: {
    titleImportCompleted: 'Import Completed Scorecard',
    titleUpload: 'Upload Scorecard',
    reviewRoundTitle: 'Review Round',
    unknownCourse: 'Unknown course',
    teeFallback: 'Tee',
    dateFallback: 'Date',
    reviewCardTitle: 'Review your scorecard',
    reviewCardBody: 'Some scores and yardages may need a quick check. Tap any cell to fix.',
    importedNotesWithPlayer: 'Imported scorecard ({playerName})',
    importedNotesDefault: 'Imported scorecard',
    sectionTabPhoto: 'Photo',
    sectionTabStats: 'Stats',
    sectionTabCourse: 'Course',
    sectionTabYardage: 'Yardage',
    scanScoresAndStats: 'Scores & stats',
    scanBackSideScores: 'Back side scores',
    scanCourseAndTees: 'Course & tees',
    scanYardagesAndPars: 'Yardages & pars',
    scanDetailPartialReview: 'Partial - review needed',
    scanDetailNotDetectedManual: 'Not detected - add manually',
    stickyNext: 'Next',
    stickySaveRound: 'Save Round',
    stickySaveCourseAndStart: 'Save Course & Start Round',
    unknownTeeName: 'Unknown',
    unknownCourseSaveOverride: 'Unknown Course',
    handicapIncompleteScores: 'Incomplete: missing scores',
    handicapNotEligibleCourse: 'Not eligible: course missing',
    handicapNotEligibleTee: 'Not eligible: tee missing',
    handicapNotEligibleRatingSlope: 'Unrated: course details missing',
    keypadTitleFallback: 'Value',
    keypadTitleScore: 'Score',
    keypadTitlePutts: 'Putts',
    keypadTitlePenalties: 'Penalties',
    keypadTitleFairway: 'Fairway',
    keypadTitleGreen: 'Green in Regulation',
    keypadTitlePar: 'Par',
    keypadTitleHcpMen: 'Hole Allowance (Men)',
    keypadTitleHcpWomen: 'Hole Allowance (Women)',
    keypadTitleYardage: 'Yardage',
    keypadTitleRatingMen: 'Men Course Difficulty',
    keypadTitleSlopeMen: 'Men Course Slope',
    keypadTitleRatingWomen: 'Women Course Difficulty',
    keypadTitleSlopeWomen: 'Women Course Slope',
    keypadChooseValue: 'Choose value',
    holeLabelPrefix: 'Hole',
    reviewStatusComplete: 'Complete',
    reviewStatusNeedsReview: 'Needs review',
    reviewChipDateNotSet: 'not set',
    reviewChipDateFallback: 'Date',
    datePickerTitle: 'Select Date',
    datePickerDone: 'Done',
    photoSectionTitle: 'Scorecard Photo',
    photoPlaceholder: 'Scorecard Photo',
    photoShowsLabel: 'What does this card show?',
    playedFullLabel: 'Did you play a full 18 holes?',
    all18Holes: 'All 18 holes',
    yesAddOtherNine: 'Yes - add the other 9',
    noNineHoleRound: 'No - 9-hole round',
    addBackCardPrompt: 'Now add the Back 9 card',
    addFrontCardPrompt: 'Now add the Front 9 card',
    front9: 'Front 9',
    back9: 'Back 9',
    roundLength: 'Round length',
    holes18: '18 Holes',
    holes9: '9 Holes',
    actionSelectFromPhotos: 'Select from Photos',
    actionTakePhoto: 'Take Photo',
    actionSelectBackPhoto: 'Select Back Photo',
    actionChangePhoto: 'Change Photo',
    actionSelectAnotherPhoto: 'Select Another Photo',
    actionScanScorecard: 'Scan Scorecard',
    progressExtracting: 'Extracting scorecard... {progress}%',
    stepsAfterSelectingPhoto: 'After selecting a photo:',
    stepsReadyToExtract: 'Ready to extract:',
    stepsExtracting: 'Extracting:',
    stepsExtractionComplete: 'Extraction complete:',
    stepsExtractionCompleteWarnings: 'Extraction complete with warnings:',
    stepsExtractionFailed: 'Extraction failed',
    scanErrorTitle: 'Could not read scorecard',
    scanErrorTry: 'Try:',
    scanErrorBulletLighting: '• Better lighting',
    scanErrorBulletFlatten: '• Flatten the card',
    scanErrorBulletCrop: '• Crop to just the scorecard',
    retryScan: 'Retry Scan',
    enterManually: 'Enter Manually',
    twoSidedOrNineTitle: 'Two-sided or 9-hole round?',
    twoSidedOrNineBody: 'We found {holes} holes. Add the back side for all 18, or confirm this is a 9-hole round.',
    actionSelectPhoto: 'Select Photo',
    statusFrontScanned: 'Front scanned',
    statusBackScanned: 'Back scanned',
    reviewInStatsTab: 'Review in Stats tab',
    courseDetailsTitle: 'Course Details',
    ratingMissingTitle: 'Course details missing',
    ratingMissingSubtitle: 'Set par and tee details for better tracking.',
    addRating: 'Add details',
    courseNamePlaceholderShort: 'Course name',
    findNearby: 'Find nearby',
    findingNearby: 'Finding...',
    searchHint: 'Type to search or pick a nearby course.',
    cityPlaceholderShort: 'City',
    statePlaceholderShort: 'State',
    countryPlaceholder: 'Country (US)',
    roundLengthTitle: 'Round Length',
    teeBoxesTitle: 'Tee Boxes',
    addTee: 'Add Tee',
    teeBoxNamePlaceholder: 'Tee box name',
    removeTee: 'Remove Tee',
    menRating: 'Men Rating',
    menSlope: 'Men Slope',
    womenRating: 'Women Rating',
    womenSlope: 'Women Slope',
    yardagesParTitle: 'Yardages & Par',
    front9Title: 'Front 9',
    back9Title: 'Back 9',
    yardageHeaderPar: 'Par',
    yardageHeaderHcp: 'HCP',
    yardageHeaderYds: 'Yds',
    yardageOut: 'OUT:',
    yardageIn: 'IN:',
    yardageParPrefix: 'Par {par}',
    yardageYdsSuffix: '• {yds} yds',
    playerStatsTitle: 'Player Stats',
    playerStatsTapToCorrect: 'Tap any value to correct',
    playerNamePlaceholder: 'Player name',
    chooseNameFromScorecard: 'Choose name from scorecard',
    headerScr: 'Scr',
    headerPtt: 'Ptt',
    headerPen: 'Pen',
    upgradeEditAdvanced: 'Track fairways, greens, scrambling, and penalties with Pro',
    trackAdvancedWithPro: 'Track fairways, greens, and miss patterns with Pro',
    showAllStats: 'Show all stats',
    puttsSuffix: '• {putts} putts',
  },
} as const;
