import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f1419',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#9CA3AF',
  },
  errorText: {
    fontSize: 16,
    color: '#EF4444',
    marginBottom: 16,
  },
  button: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#1a2028',
    borderBottomWidth: 1,
    borderBottomColor: '#2a3038',
    marginHorizontal: 12,
    marginTop: 8,
    borderRadius: 12,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    padding: 4,
  },
  headerCenter: {
    flex: 1,
    marginHorizontal: 12,
  },
  courseName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  shotgunBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  shotgunBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#F59E0B',
  },
  teeBox: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  favoriteButton: {
    padding: 4,
  },
  modePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#2a3038',
    borderWidth: 1,
    borderColor: '#374151',
  },
  modePillQuick: {
    borderColor: '#3B82F6',
  },
  modePillDetailed: {
    borderColor: '#10B981',
  },
  modePillText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  holeOverviewContainer: {
    position: 'relative',
  },
  holeOverview: {
    backgroundColor: '#0f1419',
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  entryModeToggle: {
    flexDirection: 'row',
    gap: 8,
    padding: 4,
    borderRadius: 10,
    backgroundColor: '#1a2028',
    borderWidth: 1,
    borderColor: '#2a3038',
    marginBottom: 8,
  },
  entryModeButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 8,
    alignItems: 'center',
  },
  entryModeButtonActive: {
    backgroundColor: '#10B981',
  },
  entryModeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  entryModeTextActive: {
    color: '#0f1419',
  },
  miniScorecard: {
    backgroundColor: '#111827',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: 12,
    overflow: 'hidden',
  },
  miniScorecardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  miniScorecardTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  miniScorecardChevron: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  miniScorecardGrid: {
    paddingHorizontal: 8,
    paddingBottom: 10,
    gap: 6,
  },
  miniScoreRow: {
    flexDirection: 'row',
    gap: 4,
  },
  miniScoreCell: {
    flex: 1,
    minWidth: 0,
    height: 22,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f2937',
  },
  miniScoreCellWrap: {
    flex: 1,
    minWidth: 0,
  },
  miniScoreCellEmpty: {
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  miniScoreCellBirdie: {
    backgroundColor: '#10B981',
  },
  miniScoreCellPar: {
    backgroundColor: '#4B5563',
  },
  miniScoreCellBogey: {
    backgroundColor: '#F59E0B',
  },
  miniScoreCellText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  miniScoreCellTextMuted: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  miniScoreTotalCell: {
    backgroundColor: '#0f1419',
    borderWidth: 1,
    borderColor: '#374151',
  },
  miniScoreTotalLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  miniScoreTotalValue: {
    fontSize: 11,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  miniScoreDivider: {
    height: 1,
    backgroundColor: '#1f2937',
  },
  holeOverviewFadeLeft: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 8,
    width: 20,
    backgroundColor: 'rgba(15, 20, 25, 0.9)',
  },
  holeOverviewFadeRight: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 8,
    width: 20,
    backgroundColor: 'rgba(15, 20, 25, 0.9)',
  },
  preRoundTipCard: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  weatherTipCard: {
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.3)',
  },
  preRoundTipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  preRoundTipTitle: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  preRoundTipText: {
    fontSize: 13,
    color: '#E5E7EB',
    lineHeight: 18,
  },
  holeChip: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  holeChipActive: {
    backgroundColor: '#10B981',
    borderWidth: 0,
  },
  holeChipCompleted: {
    backgroundColor: '#374151',
    borderWidth: 0,
  },
  holeChipBirdie: {
    backgroundColor: '#10B981',
  },
  holeChipPar: {
    backgroundColor: '#4B5563',
  },
  holeChipBogey: {
    backgroundColor: '#F59E0B',
  },
  holeChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  holeChipTextCompleted: {
    color: '#FFFFFF',
  },
  holeChipTextActive: {
    color: '#fff',
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    padding: 12,
    paddingTop: 8,
    paddingBottom: 180, // Space for stats summary + save button
  },
  holeCard: {
    backgroundColor: '#1a2028',
    borderRadius: 12,
    padding: 16,
    marginTop: 0,
    marginBottom: 16,
  },
  quickScoreCard: {
    backgroundColor: '#1a2028',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  quickScoreSection: {
    alignItems: 'center',
    marginTop: 12,
  },
  quickScoreRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    alignItems: 'flex-start',
  },
  quickScoreSectionCompact: {
    flex: 1,
    alignItems: 'center',
    marginTop: 0,
  },
  quickScoreLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 12,
  },
  quickScoreControl: {
    alignItems: 'center',
    backgroundColor: '#2a3038',
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  quickScoreButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickScoreValueWrap: {
    paddingVertical: 6,
  },
  quickScoreValue: {
    fontSize: 36,
    fontWeight: '700',
    color: '#10B981',
  },
  quickScoreHint: {
    marginTop: 6,
    fontSize: 11,
    color: '#6B7280',
  },
  holeHeader: {
    marginBottom: 24,
  },
  holeNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 8,
  },
  holeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  holeInfoText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  holeInfoDivider: {
    marginHorizontal: 8,
    color: '#4B5563',
  },
  scoreSection: {
    marginBottom: 24,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 12,
  },
  scoreControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
  },
  scoreButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreDisplay: {
    alignItems: 'center',
  },
  scoreValue: {
    fontSize: 48,
    fontWeight: '700',
    color: '#10B981',
  },
  scoreSubtext: {
    fontSize: 16,
    color: '#9CA3AF',
    marginTop: 4,
  },
  puttsSection: {
    marginBottom: 24,
  },
  puttsControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  puttsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  puttsValue: {
    fontSize: 32,
    fontWeight: '600',
    color: '#E5E7EB',
    minWidth: 40,
    textAlign: 'center',
  },
  statsSection: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  statToggle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#2a3038',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  statToggleHit: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  statToggleMiss: {
    borderColor: '#EF4444',
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  statToggleText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#2a3038',
    borderRadius: 8,
  },
  navButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  navButtonTextDisabled: {
    color: '#4B5563',
  },
  summaryCard: {
    backgroundColor: '#1a2028',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 16,
  },
  summaryGrid: {
    gap: 16,
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  summarySubvalue: {
    fontSize: 14,
    fontWeight: '400',
    color: '#9CA3AF',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: '#1a2028',
    borderTopWidth: 1,
    borderTopColor: '#2a3038',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingVertical: 16,
  },
  saveButtonDisabled: {
    backgroundColor: '#374151',
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },

  preRoundOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 20, 25, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  preRoundCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#1a2028',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#2a3038',
  },
  preRoundCourse: {
    fontSize: 18,
    fontWeight: '700',
    color: '#E5E7EB',
    textAlign: 'center',
  },
  preRoundMeta: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 6,
  },
  preRoundSection: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#2a3038',
  },
  preRoundSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  preRoundSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
    letterSpacing: 0.4,
  },
  preRoundSectionText: {
    fontSize: 14,
    color: '#E5E7EB',
    lineHeight: 20,
  },
  preRoundSectionSubtext: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 6,
    lineHeight: 18,
  },
  predictionBlock: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#2a3038',
  },
  predictionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 6,
  },
  predictionRangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  predictionRange: {
    fontSize: 26,
    fontWeight: '800',
    color: '#10B981',
  },
  predictionConfidenceBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: '#1f2937',
  },
  confidenceHigh: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16,185,129,0.18)',
  },
  confidenceMedium: {
    borderColor: '#F59E0B',
    backgroundColor: 'rgba(245,158,11,0.18)',
  },
  confidenceLow: {
    borderColor: '#6B7280',
    backgroundColor: 'rgba(107,114,128,0.18)',
  },
  predictionConfidenceText: {
    color: '#D1D5DB',
    fontSize: 11,
    fontWeight: '700',
  },
  predictionCondNote: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 4,
  },
  predictionBasis: {
    fontSize: 11,
    color: '#6B7280',
  },
  windDirRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  windDirChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: '#111827',
  },
  windDirChipActive: {
    borderColor: '#60A5FA',
    backgroundColor: 'rgba(96, 165, 250, 0.18)',
  },
  windDirChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  windDirChipTextActive: {
    color: '#BFDBFE',
  },
  turnWeatherBanner: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 10,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F3A5A',
    backgroundColor: 'rgba(30, 58, 95, 0.2)',
  },
  turnWeatherTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  turnWeatherBody: {
    fontSize: 12,
    color: '#9CA3AF',
    lineHeight: 18,
  },
  turnWeatherActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 10,
  },
  turnWeatherSecondary: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
  },
  turnWeatherSecondaryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D1D5DB',
  },
  turnWeatherPrimary: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#10B981',
  },
  turnWeatherPrimaryText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f1419',
  },
  preRoundStartButton: {
    marginTop: 20,
    backgroundColor: '#10B981',
    paddingVertical: 12,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  preRoundStartText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f1419',
  },
  
  // Modal styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#1a2028',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxHeight: '80%',
    maxWidth: 500,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalBackButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#E5E7EB',
    textAlign: 'center',
    flex: 1,
  },
  
  // Tee box selection
  teeBoxOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#2a3038',
    borderRadius: 12,
    marginBottom: 12,
  },
  teeBoxOptionSelected: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 1,
    borderColor: '#10B981',
  },
  teeBoxInfo: {
    flex: 1,
  },
  teeBoxName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  teeBoxDetails: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  roundOptions: {
    marginTop: 8,
    gap: 12,
  },
  roundOptionsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  // Start Type Selection
  startTypeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#2a3038',
    borderRadius: 12,
    marginBottom: 16,
    gap: 12,
  },
  startTypeIcon: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  startTypeIconShotgun: {
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
  },
  startTypeInfo: {
    flex: 1,
  },
  startTypeName: {
    fontSize: 17,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  startTypeDescription: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 4,
  },
  startTypeHelper: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  
  // Starting hole selection
  startingHoleOptions: {
    flexDirection: 'row',
    gap: 10,
  },
  startingHoleButton: {
    flex: 1,
    padding: 20,
    backgroundColor: '#2a3038',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  startingHoleButtonActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  startingHoleText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  startingHoleTextActive: {
    color: '#10B981',
  },
  startingHoleSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  startingHoleModal: {
    backgroundColor: '#1F2937',
    borderRadius: 16,
    padding: 16,
    width: '90%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#374151',
  },
  startingHoleGrid: {
    paddingVertical: 8,
  },
  startingHoleSectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  startingHoleSectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  startingHoleDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginVertical: 8,
  },
  startingHoleOption: {
    width: '30%',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: '#2a3038',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  startingHoleOptionActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  startingHoleOptionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  startingHoleOptionTextActive: {
    color: '#10B981',
  },
  teeBoxOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  teeColorStripe: {
    width: 4,
    height: 40,
    borderRadius: 2,
  },
  // Hole info at top
  holeInfoTop: {
    marginBottom: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  holeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  holeInfoCenter: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  holeNumberTop: {
    fontSize: 24,
    fontWeight: '700',
    color: '#10B981',
    marginBottom: 4,
    textAlign: 'center',
  },
  navButtonSmall: {
    width: 44,
    height: 44,
    borderRadius: 18,
    backgroundColor: '#2a3038',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navButtonDisabled: {
    opacity: 0.3,
  },
  holeDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  holeDetail: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  holeDivider: {
    marginHorizontal: 6,
    color: '#4B5563',
  },

  fullScorecardLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    marginBottom: 12,
  },
  fullScorecardLinkText: {
    fontSize: 13,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  
  // Full scorecard button
  fullScorecardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: '#2a3038',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#10B981',
  },
  fullScorecardButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10B981',
  },
  
  // Full scorecard modal
  fullScorecardModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    zIndex: 2000,
  },
  fullScorecardModal: {
    flex: 1,
    backgroundColor: '#0f1419',
  },
  fullScorecardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#1a2028',
    borderBottomWidth: 1,
    borderBottomColor: '#2a3038',
  },
  fullScorecardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#E5E7EB',
    flex: 1,
    textAlign: 'center',
  },
  fullScorecardContent: {
    flex: 1,
    padding: 16,
  },
  fullScorecardCourseName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  fullScorecardTeeInfo: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 20,
  },
  fullScorecardTable: {
    marginTop: 12,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#374151',
  },
  fullScorecardHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#2a3038',
  },
  fullScorecardHeaderCell: {
    width: 44,
    paddingVertical: 8,
    paddingHorizontal: 4,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
    color: '#10B981',
    borderWidth: 1,
    borderColor: '#374151',
  },
  fullScorecardRow: {
    flexDirection: 'row',
    backgroundColor: '#1a2028',
  },
  fullScorecardCell: {
    width: 44,
    paddingVertical: 8,
    paddingHorizontal: 4,
    textAlign: 'center',
    fontSize: 11,
    color: '#9CA3AF',
    borderWidth: 1,
    borderColor: '#374151',
  },
  fullScorecardScoreOuter: {
    minWidth: 26,
    height: 26,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  fullScorecardScoreInner: {
    position: 'absolute',
    top: 3,
    left: 3,
    right: 3,
    bottom: 3,
    borderWidth: 2,
  },
  fullScorecardScoreCircle: {
    borderRadius: 999,
  },
  fullScorecardScoreSquare: {
    borderRadius: 4,
  },
  fullScorecardScoreText: {
    fontSize: 12,
    fontWeight: '700',
  },
  fullScorecardScorePar: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E5E7EB',
    textAlign: 'center',
  },
  fullScorecardScoreMuted: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textAlign: 'center',
  },
  fullScorecardActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 16,
  },
  fullScorecardActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  fullScorecardActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#10B981',
  },
  // Compact Score & Putts styles
  scorePuttsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  scoreContainerPrimary: {
    flex: 0.55,
  },
  scoreContainerSecondary: {
    flex: 0.45,
  },
  scoreContainer: {
    flex: 1,
  },
  scoreLabelPrimary: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  scoreLabelSecondary: {
    fontSize: 13,
    fontWeight: '500',
    color: '#9CA3AF',
    marginBottom: 6,
  },
  scoreLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 6,
  },
  scoreControlCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a3038',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3c4450',
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  compactButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactButtonPrimary: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreDisplayCompact: {
    minWidth: 48,
    alignItems: 'center',
  },
  scoreValuePrimary: {
    fontSize: 48,
    fontWeight: '700',
    color: '#E5E7EB',
    lineHeight: 52,
  },
  scoreValueSecondary: {
    fontSize: 32,
    fontWeight: '600',
    color: '#E5E7EB',
    lineHeight: 36,
  },
  scorePenaltyHint: {
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 6,
    marginLeft: 2,
  },
  scoreValueCompact: {
    fontSize: 30,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  // Shots Row (Tee Shot and Approach)
  shotsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
    justifyContent: 'space-around',
  },
  shotColumn: {
    flex: 1,
    alignItems: 'stretch',
  },
  shotLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 6,
  },
  hitMissRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 6,
  },
  hitMissButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    paddingHorizontal: 8,
  },
  hitMissButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderColor: '#10B981',
  },
  hitMissButtonMiss: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: '#EF4444',
  },
  hitMissButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  hitMissButtonTextActive: {
    color: '#10B981',
  },
  hitMissButtonTextMiss: {
    color: '#EF4444',
  },
  compactDirectionGrid: {
    padding: 6,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
  },
  compactDirectionRow: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    marginVertical: 3,
  },
  compactDirectionRowCenter: {
    alignItems: 'center',
    marginVertical: 3,
  },
  compactDirectionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#374151',
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(17,24,39,0.6)',
  },
  compactDirectionButtonActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  compactDirectionText: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  compactDirectionTextActive: {
    color: '#10B981',
    fontWeight: '600',
  },
  directionRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  directionPad: {
    gap: 6,
    alignItems: 'stretch',
    width: '100%',
  },
  directionPadRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  directionPadRowCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  directionPadButton: {
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    flex: 1,
    minWidth: 0,
  },
  directionPadButtonSolo: {
    flex: 0,
    width: '55%',
    minWidth: 86,
  },
  directionPadButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderColor: '#10B981',
  },
  directionPadText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    marginTop: 2,
  },
  directionPadTextActive: {
    color: '#10B981',
  },
  directionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  directionButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderColor: '#10B981',
  },
  directionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  directionButtonTextActive: {
    color: '#10B981',
  },
  // Club selector
  clubSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a3038',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  clubText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  clubSelectorSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#2a3038',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 4,
    minHeight: 44,
    width: '100%',
  },
  clubTextSmall: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  collapsibleContainer: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
  },
  collapsibleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
  },
  collapsibleHeaderContent: {
    flex: 1,
    paddingRight: 8,
  },
  collapsibleTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  collapsibleSubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 2,
  },
  collapsibleContent: {
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  compactRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  compactField: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  microLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 4,
  },
  compactValue: {
    fontSize: 13,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  compactValuePlaceholder: {
    color: '#9CA3AF',
    fontWeight: '500',
  },
  holeNotesList: {
    gap: 8,
    marginBottom: 10,
  },
  holeNotesCompact: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 12,
    marginBottom: 12,
  },
  holeNotesCompactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  holeNotesCompactTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  holeNotesCompactTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  holeNotesDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10B981',
  },
  holeNoteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  holeNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#D1D5DB',
    lineHeight: 17,
  },
  holeNoteDate: {
    color: '#9CA3AF',
    fontWeight: '600',
  },
  holeNoteDelete: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  holeNoteComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  holeNoteInput: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: '#111827',
    paddingHorizontal: 10,
    color: '#E5E7EB',
    fontSize: 13,
  },
  holeNoteInputCompact: {
    minHeight: 40,
    maxHeight: 88,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: '#111827',
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: '#E5E7EB',
    fontSize: 13,
    textAlignVertical: 'center',
  },
  holeNoteInputCompactExpanded: {
    textAlignVertical: 'top',
  },
  holeNotesCompactActions: {
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  holeNoteSaveButton: {
    minHeight: 40,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a3038',
    borderWidth: 1,
    borderColor: '#3B4A5A',
  },
  holeNoteSaveButtonDisabled: {
    opacity: 0.45,
  },
  holeNoteSaveText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D1D5DB',
  },
  clubList: {
    maxHeight: 400,
  },
  clubOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2a3038',
  },
  clubOptionSelected: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
  },
  clubOptionText: {
    fontSize: 16,
    color: '#E5E7EB',
  },
  clubOptionTextSelected: {
    color: '#10B981',
    fontWeight: '600',
  },
  // Stats row (bunkers, penalties)
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
    justifyContent: 'space-around',
  },
  approachDistanceSection: {
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  approachDistanceLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 8,
  },
  scrambleSection: {
    marginBottom: 12,
    paddingHorizontal: 6,
  },
  scrambleLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 6,
  },
  scrambleHelper: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  scrambleButtons: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  scrambleButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    gap: 4,
  },
  scrambleButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderColor: '#10B981',
  },
  scrambleButtonMiss: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: '#EF4444',
  },
  scrambleButtonDisabled: {
    opacity: 0.5,
  },
  scrambleButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  scrambleButtonTextActive: {
    color: '#10B981',
  },
  scrambleButtonTextMiss: {
    color: '#EF4444',
  },
  addPenaltyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#121820',
    borderWidth: 1,
    borderColor: '#2a3038',
    minHeight: 44,
  },
  addPenaltyButtonText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#D1D5DB',
  },
  badge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#10B981',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  badgePenalty: {
    backgroundColor: '#EF4444',
  },
  badgeNeutral: {
    backgroundColor: '#4B5563',
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  sheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
    zIndex: 2000,
  },
  sheetContainer: {
    backgroundColor: '#111827',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 16,
    maxHeight: '80%',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1f2937',
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  sheetContent: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 16,
  },
  sheetSection: {
    gap: 10,
  },
  sheetLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  sheetButtonRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  sheetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
  },
  sheetButtonActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  sheetButtonText: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  sheetButtonTextActive: {
    color: '#10B981',
    fontWeight: '600',
  },
  sheetDoneButton: {
    marginTop: 4,
    marginHorizontal: 16,
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  sheetDoneButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  distanceBucketsScroll: {
    flexDirection: 'row',
  },
  distanceBucket: {
    backgroundColor: '#2a3038',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#374151',
  },
  distanceBucketActive: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  distanceBucketText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#9CA3AF',
  },
  distanceBucketTextActive: {
    color: '#FFFFFF',
  },
  statsGroup: {
    flex: 1,
  },
  statsGroupLeft: {
    alignItems: 'flex-start',
  },
  statsGroupLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 8,
    textAlign: 'center',
  },
  statsGroupLabelLeft: {
    textAlign: 'left',
  },
  statsButtons: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  statsButtonsLeft: {
    justifyContent: 'flex-start',
  },
  statsButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    flexWrap: 'nowrap',
  },
  statButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2a3038',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 6,
    minWidth: 0,
    minHeight: 44,
  },
  statButtonWide: {
    flex: 1,
    minWidth: 0,
  },
  statButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 2,
    borderColor: '#10B981',
  },
  statButtonText: {
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 6,
  },
  statButtonTextActive: {
    color: '#10B981',
    fontWeight: '600',
  },
  // Basic Mode Stats (Simple Toggles)
  basicStatsSection: {
    gap: 8,
    marginBottom: 12,
  },
  basicStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  basicStatLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
    flex: 1,
  },
  basicStatButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  basicStatButton: {
    backgroundColor: '#1f2937',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#374151',
    minHeight: 44,
  },
  basicStatButtonHit: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: '#10B981',
  },
  basicStatButtonMiss: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: '#EF4444',
  },
  basicStatButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  basicStatButtonTextActive: {
    color: '#10B981',
  },
  basicStatButtonTextMiss: {
    color: '#EF4444',
  },
  par3FirHintRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  par3FirHintDash: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6B7280',
    minWidth: 12,
    textAlign: 'center',
  },
  par3FirHintText: {
    fontSize: 12,
    color: '#6B7280',
  },
  // Round Summary - Full Screen
  roundSummaryFullScreen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#0f1419',
    zIndex: 1000,
  },
  roundSummaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    paddingTop: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#2a3038',
    backgroundColor: '#0f1419',
  },
  roundSummaryTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  roundSummaryContent: {
    flex: 1,
    padding: 20,
    paddingBottom: 100, // Space for footer + nav
  },
  roundSummaryCourseName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  roundSummaryTeeInfo: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
  },
  // S+ TIER: Round Theme
  roundThemeCard: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  roundTheme: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10B981',
    fontStyle: 'italic',
  },
  summaryStatsCard: {
    backgroundColor: '#2a3038',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  summaryStatRow: {
    alignItems: 'center',
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
    marginBottom: 16,
  },
  summaryStatLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
    marginBottom: 4,
  },
  summaryStatValueLarge: {
    fontSize: 48,
    fontWeight: '700',
    color: '#10B981',
  },
  summaryStatSubtext: {
    fontSize: 16,
    color: '#9CA3AF',
  },
  summaryStatsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  summaryStatItem: {
    alignItems: 'center',
  },
  summaryStatValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  // S+ TIER: Key Takeaways (Max 2)
  takeawaysCard: {
    backgroundColor: '#2a3038',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    gap: 16,
  },
  takeawayRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  takeawayIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  takeawayContent: {
    flex: 1,
  },
  takeawayLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  takeawayText: {
    fontSize: 15,
    color: '#E5E7EB',
    lineHeight: 21,
  },
  summaryBreakdownTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 12,
    marginTop: 8,
  },
  summaryHoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2a3038',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  summaryHoleNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  summaryHoleNumberText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  summaryHoleInfo: {
    flex: 1,
  },
  summaryHoleText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  summaryHoleScore: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryHoleScoreText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  summaryHoleScoreBirdie: {
    color: '#10B981',
  },
  summaryHoleScoreBogey: {
    color: '#F59E0B',
  },
  roundProgressCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  roundProgressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  roundProgressTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  roundProgressValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  roundProgressBar: {
    height: 6,
    backgroundColor: '#1F2937',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 12,
  },
  roundProgressFill: {
    height: '100%',
    backgroundColor: '#10B981',
    minWidth: 0,
  },
  roundProgressStats: {
    gap: 8,
  },
  roundProgressStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  roundProgressStat: {
    alignItems: 'center',
    flex: 1,
  },
  roundProgressStatValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  roundProgressStatLabel: {
    fontSize: 10,
    color: '#9CA3AF',
    marginTop: 4,
  },
  roundProgressStatGood: {
    color: '#10B981',
  },
  roundProgressStatBad: {
    color: '#EF4444',
  },
  liveIntelStrip: {
    marginTop: 4,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#253140',
    gap: 4,
  },
  liveIntelPrimary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  liveIntelLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D1D5DB',
  },
  liveIntelValue: {
    fontSize: 12,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  liveIntelPositive: {
    color: '#10B981',
  },
  liveIntelNegative: {
    color: '#EF4444',
  },
  liveIntelDetail: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  liveIntelSecondary: {
    fontSize: 11,
    color: '#94A3B8',
  },
  ghostRow: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#253140',
    paddingTop: 8,
  },
  ghostText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  ghostAhead: {
    color: '#10B981',
  },
  ghostBehind: {
    color: '#F87171',
  },
  ghostTied: {
    color: '#9CA3AF',
  },
  ghostHoleTarget: {
    marginTop: 4,
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  comebackCard: {
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#F59E0B',
    borderRadius: 10,
    backgroundColor: 'rgba(245,158,11,0.08)',
    padding: 10,
  },
  comebackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  comebackLabel: {
    color: '#F59E0B',
    fontSize: 12,
    fontWeight: '700',
  },
  comebackMessage: {
    color: '#E5E7EB',
    fontSize: 12,
    lineHeight: 18,
  },
  comebackSecondary: {
    marginTop: 4,
    color: '#9CA3AF',
    fontSize: 11,
  },
  holeReadBanner: {
    marginHorizontal: 16,
    marginBottom: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#253140',
  },
  holeReadText: {
    textAlign: 'center',
    fontSize: 13,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  holeReadGreat: {
    color: '#10B981',
  },
  holeReadGood: {
    color: '#34D399',
  },
  holeReadBad: {
    color: '#F87171',
  },
  holeReadReset: {
    color: '#6B7280',
    fontStyle: 'italic',
  },
  roundSummaryFooter: {
    padding: 16,
    paddingBottom: 90, // Space for bottom navigation
    borderTopWidth: 1,
    borderTopColor: '#2a3038',
    backgroundColor: '#0f1419',
  },
  // Confirmation Modals
  modalOverlayDark: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
    padding: 20,
  },
  confirmModal: {
    backgroundColor: '#1F2937',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
  },
  confirmModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 12,
    textAlign: 'center',
  },
  confirmModalMessage: {
    fontSize: 15,
    color: '#9CA3AF',
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  confirmModalButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 12,
    backgroundColor: '#374151',
  },
  confirmModalButtonPrimary: {
    backgroundColor: '#10B981',
  },
  confirmModalButtonDestructive: {
    backgroundColor: '#EF4444',
  },
  confirmModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  confirmModalButtonTextSecondary: {
    color: '#9CA3AF',
  },
  confirmModalButtonTextDestructive: {
    color: '#FCA5A5',
  },
  reasonButton: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#374151',
    marginBottom: 10,
  },
  reasonButtonText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#E5E7EB',
    marginLeft: 12,
  },
});
