import { styles } from '../../ScorecardImportScreen.styles';
import type { useDeferredHandlers } from './useDeferredHandlers';
import type { useImportCallbacks } from './useImportCallbacks';
import type { useImportMainSectionsProps } from './useImportMainSectionsProps';
import type { ScorecardImportLayoutModelParams } from './useScorecardImportLayoutModel.types';

type MainSectionsArgs = Parameters<typeof useImportMainSectionsProps>[0];

export function useImportMainSectionsArgs(
  params: ScorecardImportLayoutModelParams,
  deferredHandlers: ReturnType<typeof useDeferredHandlers>,
  importCallbacks: ReturnType<typeof useImportCallbacks>
): MainSectionsArgs {
  return {
    isCompletedMode: params.isCompletedMode,
    activeSection: params.activeSection,
    styles,
    isPremium: params.isPremium,
    inTrial: params.inTrial,
    playerName: params.playerName,
    playerDate: params.playerDate,
    playerDateDisplay: params.playerDateDisplay,
    playerNameCandidates: params.playerNameCandidates,
    playerNineView: params.playerNineView,
    focusedHoleIndex: params.focusedHoleIndex,
    pars: params.pars,
    hcpMen: params.hcpMen,
    scores: params.scores,
    putts: params.putts,
    fairways: params.fairways,
    greens: params.greens,
    upDowns: params.upDowns,
    penalties: params.penalties,
    lockedFields: params.lockedFields,
    showAllStatsColumns: params.showAllStatsColumns,
    fairwayEditMode: params.fairwayEditMode,
    greenEditMode: params.greenEditMode,
    playerNineRange: params.playerNineRange,
    openKeypad: params.openKeypad,
    openFlagPicker: params.openFlagPicker,
    toggleFlag: params.toggleFlag,
    toggleUpDown: params.toggleUpDown,
    setFocusedHoleIndex: params.setFocusedHoleIndex,
    renderArrowValue: params.renderArrowValue,
    showDeferredSections: params.showDeferredSections,
    hasValidRating: params.hasValidRating,
    roundHoleCount: params.roundHoleCount,
    scanState: params.scanState,
    scanProgress: params.scanProgress,
    scanSteps: params.scanSteps,
    hasScanWarnings: params.hasScanWarnings,
    isProcessing: params.isProcessing,
    scanSide: params.scanSide,
    cardConfig: params.cardConfig,
    imageUri: params.imageUri,
    backImageUri: params.backImageUri,
    courseSearchQuery: params.courseSearchQuery,
    courseSearchLoading: params.courseSearchLoading,
    showCourseSuggestions: params.showCourseSuggestions,
    courseSearchResults: params.courseSearchResults,
    city: params.city,
    state: params.state,
    country: params.country,
    teeBoxes: params.teeBoxes,
    activeTeeIndex: params.activeTeeIndex,
    yardageWidths: params.yardageWidths,
    onSelectImage: params.handleSelectImage,
    onTakePhoto: params.handleTakePhoto,
    onChangePhoto: params.handleChangePhoto,
    onRunOcr: params.handleRunOCR,
    onEnterManual: deferredHandlers.onEnterManual,
    onReviewStats: deferredHandlers.onReviewStats,
    onAddBackSide: params.handleAddBackSide,
    onTakeBackPhoto: params.handleTakeBackPhoto,
    onSetCoverage: params.handleSetCoverage,
    onSetPlayedFull: params.handleSetPlayedFull,
    onSetRoundHoleCount: params.handleSetRoundHoleCount,
    onAddRating: deferredHandlers.onAddRating,
    onCourseSearchChange: deferredHandlers.onCourseSearchChange,
    onCourseSearchFocus: deferredHandlers.onCourseSearchFocus,
    onFindNearby: params.handleFindNearbyCourses,
    onSelectCourseSuggestion: params.applyCourseSuggestion,
    onCityChange: deferredHandlers.onCityChange,
    onStateChange: deferredHandlers.onStateChange,
    onCountryChange: deferredHandlers.onCountryChange,
    onSelectTee: params.setActiveTeeIndex,
    onAddTee: deferredHandlers.onAddTee,
    onRemoveTee: deferredHandlers.onRemoveTee,
    onTeeNameChange: deferredHandlers.onTeeNameChange,
    onOpenNumeric: importCallbacks.onOpenNumeric,
    onYardageLayout: deferredHandlers.onYardageLayout,
    onUpgradeImport: importCallbacks.onUpgradeImport,
    onShowNamePicker: importCallbacks.onShowNamePicker,
    onPlayerNameChange: importCallbacks.onPlayerNameChange,
    onDatePress: params.openDatePicker,
    onNineViewChange: importCallbacks.onNineViewChange,
    onShowAllStats: importCallbacks.onShowAllStats,
  };
}
