import type { usePlayerStatsPanelProps } from './usePlayerStatsPanelProps';
import type { useDeferredSectionsProps } from './useDeferredSectionsProps';
import type { UseImportMainSectionsParams } from './useImportMainSectionsProps';

type PlayerStatsPanelArgs = Parameters<typeof usePlayerStatsPanelProps>[0];
type DeferredSectionsArgs = Parameters<typeof useDeferredSectionsProps>[0];

export function buildPlayerStatsPanelArgs(params: UseImportMainSectionsParams): PlayerStatsPanelArgs {
  return {
    isCompletedMode: params.isCompletedMode,
    activeSection: params.activeSection,
    styles: params.styles,
    isPremium: params.isPremium,
    inTrial: params.inTrial,
    onUpgrade: params.onUpgradeImport,
    playerName: params.playerName,
    playerDate: params.playerDate,
    playerDateDisplay: params.playerDateDisplay,
    playerNameCandidates: params.playerNameCandidates,
    onShowNamePicker: params.onShowNamePicker,
    onPlayerNameChange: params.onPlayerNameChange,
    onDatePress: params.onDatePress,
    playerNineView: params.playerNineView,
    onNineViewChange: params.onNineViewChange,
    focusedHoleIndex: params.focusedHoleIndex,
    pars: params.pars,
    hcpMen: params.hcpMen,
    scores: params.scores,
    putts: params.putts,
    fairways: params.fairways,
    greens: params.greens,
    upDowns: params.upDowns,
    penalties: params.penalties,
    editedScores: params.lockedFields.scores,
    editedPutts: params.lockedFields.putts,
    editedFairways: params.lockedFields.fairways,
    editedGreens: params.lockedFields.greens,
    editedUpDowns: params.lockedFields.upDowns,
    editedPenalties: params.lockedFields.penalties,
    showAllStatsColumns: params.showAllStatsColumns,
    onShowAllStats: params.onShowAllStats,
    fairwayEditMode: params.fairwayEditMode,
    greenEditMode: params.greenEditMode,
    playerNineRange: params.playerNineRange,
    openKeypad: params.openKeypad,
    onOpenFlagPicker: params.openFlagPicker,
    onToggleFlag: params.toggleFlag,
    onToggleUpDown: params.toggleUpDown,
    onFocusHole: params.setFocusedHoleIndex,
    renderArrowValue: params.renderArrowValue,
  };
}

export function buildDeferredSectionsArgs(params: UseImportMainSectionsParams): DeferredSectionsArgs {
  return {
    showDeferredSections: params.showDeferredSections,
    activeSection: params.activeSection,
    styles: params.styles,
    isCompletedMode: params.isCompletedMode,
    hasValidRating: params.hasValidRating,
    roundHoleCount: params.roundHoleCount,
    scanState: params.scanState,
    scanProgress: params.scanProgress,
    scanSteps: params.scanSteps,
    hasScanWarnings: params.hasScanWarnings,
    isProcessing: params.isProcessing,
    scanSide: params.scanSide,
    cardConfig: params.cardConfig,
    imageUri: params.imageUri,
    backImageUri: params.backImageUri,
    courseSearchQuery: params.courseSearchQuery,
    courseSearchLoading: params.courseSearchLoading,
    showCourseSuggestions: params.showCourseSuggestions,
    courseSearchResults: params.courseSearchResults,
    city: params.city,
    state: params.state,
    country: params.country,
    teeBoxes: params.teeBoxes,
    activeTeeIndex: params.activeTeeIndex,
    pars: params.pars,
    hcpMen: params.hcpMen,
    yardageWidths: params.yardageWidths,
    onSelectImage: params.onSelectImage,
    onTakePhoto: params.onTakePhoto,
    onChangePhoto: params.onChangePhoto,
    onRunOcr: params.onRunOcr,
    onEnterManual: params.onEnterManual,
    onReviewStats: params.onReviewStats,
    onAddBackSide: params.onAddBackSide,
    onTakeBackPhoto: params.onTakeBackPhoto,
    onSetCoverage: params.onSetCoverage,
    onSetPlayedFull: params.onSetPlayedFull,
    onSetRoundHoleCount: params.onSetRoundHoleCount,
    onAddRating: params.onAddRating,
    onCourseSearchChange: params.onCourseSearchChange,
    onCourseSearchFocus: params.onCourseSearchFocus,
    onFindNearby: params.onFindNearby,
    onSelectCourseSuggestion: params.onSelectCourseSuggestion,
    onCityChange: params.onCityChange,
    onStateChange: params.onStateChange,
    onCountryChange: params.onCountryChange,
    onSelectTee: params.onSelectTee,
    onAddTee: params.onAddTee,
    onRemoveTee: params.onRemoveTee,
    onTeeNameChange: params.onTeeNameChange,
    onOpenNumeric: params.onOpenNumeric,
    onYardageLayout: params.onYardageLayout,
  };
}
