import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f1419',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    // Vertical padding + status-bar inset applied in AppRoot when tabs are shown
    backgroundColor: '#1a2028',
    borderBottomWidth: 1,
    borderBottomColor: '#2a3038',
  },
  
  offlineBadge: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  offlineBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#F87171',
    letterSpacing: 0.3,
  },
  mainContent: {
    flex: 1,
  },
  onboardingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 20, 25, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    zIndex: 10,
  },
  onboardingCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#1a2028',
    borderRadius: 20,
    padding: 28,
    alignItems: 'center',
  },
  onboardingTopSkip: {
    alignSelf: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#242d38',
    borderWidth: 1,
    borderColor: '#2a3442',
    marginBottom: 10,
  },
  
  onboardingTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 20,
    textAlign: 'center',
  },
  onboardingTitleLeft: {
    fontSize: 22,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 20,
    textAlign: 'left',
    width: '100%',
  },
  onboardingDescription: {
    fontSize: 15,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 28,
  },
  onboardingDescriptionLeft: {
    fontSize: 15,
    color: '#9CA3AF',
    textAlign: 'left',
    lineHeight: 22,
    marginBottom: 28,
    width: '100%',
  },
  onboardingPrimaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#10B981',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: '100%',
  },
  onboardingPrimaryButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f1419',
  },
  onboardingStepRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#242d38',
    borderWidth: 1,
    borderColor: '#2a3442',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
  },
  onboardingStepText: {
    flex: 1,
  },
  onboardingStepTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#E5E7EB',
    marginBottom: 2,
  },
  onboardingStepBody: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 18,
  },
  onboardingFieldLabel: {
    alignSelf: 'flex-start',
    fontSize: 13,
    fontWeight: '700',
    color: '#9CA3AF',
    marginBottom: 8,
    marginTop: 4,
  },
  onboardingChoiceWrap: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  onboardingChoice: {
    borderWidth: 1,
    borderColor: '#2a3442',
    backgroundColor: '#242d38',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  onboardingChoiceActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
  },
  onboardingChoiceText: {
    fontSize: 13,
    color: '#CBD5E1',
    fontWeight: '600',
  },
  onboardingChoiceTextActive: {
    color: '#10B981',
  },
  onboardingChoiceColumn: {
    width: '100%',
    gap: 10,
    marginBottom: 12,
  },
  onboardingPathCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#242d38',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    width: '100%',
    borderWidth: 1,
    borderColor: '#2a3442',
  },
  onboardingPathCardActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
  },
  onboardingPathIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  onboardingPathTextContainer: {
    flex: 1,
  },
  onboardingPathTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 3,
  },
  onboardingPathDesc: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 18,
  },
  onboardingSkipButton: {
    marginTop: 4,
    paddingVertical: 8,
  },
  onboardingSkip: {
    fontSize: 15,
    color: '#E5E7EB',
    fontWeight: '700',
  },
  onboardingHint: {
    width: '100%',
    fontSize: 13,
    lineHeight: 18,
    color: '#9CA3AF',
    marginBottom: 12,
  },
  // Used by sample prompt & import prompt overlays
  onboardingActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  onboardingNext: {
    backgroundColor: '#10B981',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
  },
  onboardingNextText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f1419',
  },
  uploadTab: {
    flex: 1,
    backgroundColor: '#0f1419',
  },
  uploadScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 36,
  },
  uploadContent: {
    width: '100%',
    alignItems: 'center',
  },
  uploadTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#E5E7EB',
    marginTop: 4,
    marginBottom: 10,
    textAlign: 'center',
  },
  uploadDescription: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'left',
    width: '100%',
    marginBottom: 32,
    lineHeight: 24,
  },
  offlineRoundBanner: {
    width: '100%',
    backgroundColor: 'rgba(245, 158, 11, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.4)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: -12,
    marginBottom: 16,
  },
  offlineRoundBannerText: {
    fontSize: 12,
    color: '#FDE68A',
    fontWeight: '600',
    textAlign: 'center',
  },
  resumeBanner: {
    width: '100%',
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    padding: 16,
    marginBottom: 20,
  },
  resumeBannerText: {
    marginBottom: 12,
  },
  resumeBannerTitle: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.6,
    color: '#10B981',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  resumeBannerSubtitle: {
    fontSize: 15,
    color: '#E5E7EB',
  },
  resumeBannerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  resumeBannerSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  resumeBannerSecondaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E5E7EB',
  },
  resumeBannerPrimary: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#10B981',
  },
  resumeBannerPrimaryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f1419',
  },
  startButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#10B981',
    paddingVertical: 12,
    width: '100%',
    borderRadius: 12,
    marginBottom: 10,
  },
  startButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f1419',
  },
  importScorecardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 12,
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    marginBottom: 18,
  },
  importScorecardText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  importHint: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 24,
    marginTop: -16,
    lineHeight: 17,
  },
  setupNote: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 18,
  },
  featuresList: {
    alignItems: 'flex-start',
    alignSelf: 'center',
    gap: 12,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  featureText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
});
