export enum PatternInsightType {
  FAIRWAYS_MISSED_RIGHT = 'FAIRWAYS_MISSED_RIGHT',
  FAIRWAYS_MISSED_LEFT = 'FAIRWAYS_MISSED_LEFT',
  APPROACHES_MISSED_SHORT = 'APPROACHES_MISSED_SHORT',
  APPROACHES_MISSED_LONG = 'APPROACHES_MISSED_LONG',
  GREENS_MISSED_LEFT = 'GREENS_MISSED_LEFT',
  GREENS_MISSED_RIGHT = 'GREENS_MISSED_RIGHT',
  HIGH_THREE_PUTT = 'HIGH_THREE_PUTT',
  LOW_SHORT_PUTT_MAKE_RATE = 'LOW_SHORT_PUTT_MAKE_RATE',
  PENALTIES_HURTING_SCORES = 'PENALTIES_HURTING_SCORES',
  WIND_FAIRWAY_ACCURACY_DROP = 'WIND_FAIRWAY_ACCURACY_DROP',
  LOW_UP_DOWN_RATE = 'LOW_UP_DOWN_RATE',
  POOR_BUNKER_SAVES = 'POOR_BUNKER_SAVES',
  WEAK_PAR3_SCORING = 'WEAK_PAR3_SCORING',
  POOR_PAR5_SCORING = 'POOR_PAR5_SCORING',
  APPROACH_DISTANCE_WEAKNESS = 'APPROACH_DISTANCE_WEAKNESS',
  BACK_NINE_SCORING_DROP = 'BACK_NINE_SCORING_DROP',
  PAR4_SCORING_STRUGGLE = 'PAR4_SCORING_STRUGGLE',
  HIGH_BOGEY_CONVERSION = 'HIGH_BOGEY_CONVERSION',
  FRONT_NINE_BLOWUP = 'FRONT_NINE_BLOWUP',
  WEATHER_SCORING_DROP = 'WEATHER_SCORING_DROP',
  APPROACH_CONTACT_INCONSISTENCY = 'APPROACH_CONTACT_INCONSISTENCY',
  BETWEEN_CLUBS_HESITATION = 'BETWEEN_CLUBS_HESITATION',
}

export type HandicapTier = 'SCRATCH' | 'LOW' | 'MID' | 'HIGH' | 'BEGINNER';

export enum StrengthLevel {
  MODERATE = 'MODERATE',
  STRONG = 'STRONG',
  VERY_STRONG = 'VERY_STRONG',
}
