import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f1419',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  backButtonTop: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#252d38',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 14,
  },
  profileHeaderText: {
    flex: 1,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#1a2028',
    borderWidth: 2,
    borderColor: '#2a3038',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarSignedIn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderWidth: 2,
    borderColor: '#10B981',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarInitial: {
    fontSize: 22,
    fontWeight: '700',
    color: '#10B981',
  },
  guestText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  userName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  userEmail: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  nicknameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  nicknameEditContainer: {
    alignItems: 'flex-start',
  },
  nicknameText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  nicknameEditButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1a2028',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nicknameInput: {
    minWidth: 160,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2a3038',
    paddingHorizontal: 10,
    paddingVertical: 6,
    color: '#FFFFFF',
    backgroundColor: '#1a2028',
  },
  nicknameHint: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 4,
  },
  saveToast: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 12,
  },
  saveToastText: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '600',
  },
  subText: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  section: {
    backgroundColor: '#1a2028',
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2a3038',
    overflow: 'hidden',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#10B981',
    letterSpacing: 0.5,
    padding: 16,
    paddingBottom: 8,
  },
  groupHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6B7280',
    letterSpacing: 1,
    marginTop: 8,
    marginBottom: 12,
    marginHorizontal: 4,
  },
  syncRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  syncInfo: {
    flex: 1,
  },
  syncValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  syncLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  syncValue: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  syncValueStale: {
    color: '#F59E0B',
  },
  syncValueCritical: {
    color: '#EF4444',
  },
  syncButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  syncButtonDisabled: {
    opacity: 0.7,
  },
  syncButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f1419',
  },
  exportButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  exportButtonGroup: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  exportButtonSecondary: {
    backgroundColor: '#1f2937',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#374151',
  },
  exportButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f1419',
  },
  exportButtonTextSecondary: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  syncHint: {
    fontSize: 12,
    color: '#6B7280',
    lineHeight: 16,
  },
  syncErrorText: {
    fontSize: 12,
    color: '#FCA5A5',
    marginBottom: 6,
  },
  reportIssueText: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '600',
    marginBottom: 6,
  },
  reportIssueInput: {
    minHeight: 90,
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#E5E7EB',
    backgroundColor: '#111827',
    fontSize: 13,
    marginTop: 10,
    marginBottom: 10,
  },
  reportIssueButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  reportIssueButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f1419',
  },
  reportIssueSuccessText: {
    fontSize: 12,
    color: '#34D399',
    marginBottom: 6,
  },
  reportIssueStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  reportIssueList: {
    marginBottom: 12,
    gap: 8,
  },
  reportIssueListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2a3038',
    backgroundColor: '#111827',
  },
  reportIssueListItemActive: {
    borderColor: '#10B981',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
  },
  reportIssueListBody: {
    flex: 1,
  },
  reportIssueListMessage: {
    fontSize: 13,
    color: '#E5E7EB',
    marginBottom: 4,
  },
  reportIssueListMeta: {
    fontSize: 11,
    color: '#6B7280',
  },
  reportIssueNewBadge: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.4)',
  },
  reportIssueNewBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#10B981',
  },
  reportIssueDetail: {
    marginBottom: 12,
  },
  reportIssueThread: {
    gap: 8,
    marginBottom: 10,
  },
  reportIssueThreadItem: {
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  reportIssueThreadAdmin: {
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  reportIssueThreadUser: {
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  reportIssueThreadLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  reportIssueThreadMessage: {
    fontSize: 13,
    color: '#E5E7EB',
    lineHeight: 18,
  },
  reportIssueThreadMeta: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 6,
  },
  reportIssueHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  reportIssueRefreshButton: {
    backgroundColor: '#1f2937',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#374151',
  },
  reportIssueRefreshText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  reportIssueStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  reportIssueStatusBadgeOpen: {
    backgroundColor: 'rgba(245, 158, 11, 0.2)',
  },
  reportIssueStatusBadgeCompleted: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
  },
  reportIssueStatusText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#E5E7EB',
    textTransform: 'uppercase',
  },
  reportIssueStatusMeta: {
    fontSize: 11,
    color: '#9CA3AF',
  },
  reportIssueNoteLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  reportIssueNoteText: {
    fontSize: 12,
    color: '#E5E7EB',
    lineHeight: 16,
  },
  reportIssueLatestBox: {
    backgroundColor: '#111827',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2a3038',
    padding: 12,
    marginBottom: 10,
  },
  reportIssueLatestLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  reportIssueLatestMessage: {
    fontSize: 13,
    color: '#E5E7EB',
    lineHeight: 18,
  },
  reportIssueLatestMeta: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 6,
  },
  reportIssueReplyInput: {
    minHeight: 70,
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#E5E7EB',
    backgroundColor: '#111827',
    fontSize: 13,
    marginBottom: 8,
  },
  reportUpdateBanner: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderColor: 'rgba(16, 185, 129, 0.35)',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  reportUpdateBannerText: {
    fontSize: 12,
    color: '#E5E7EB',
    fontWeight: '600',
    flex: 1,
  },
  reportUpdateBannerAction: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '700',
  },
  syncWarningText: {
    fontSize: 12,
    color: '#F59E0B',
    marginBottom: 6,
  },
  syncWarningTextCritical: {
    color: '#EF4444',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#252d38',
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#252d38',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingInfo: {
    flex: 1,
    marginLeft: 12,
  },
  settingLabel: {
    fontSize: 15,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  settingValue: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  signInButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#10B981',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
  },
  signInButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  signOutButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#E07575',
  },
  deleteAccountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(127, 29, 29, 0.2)',
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'rgba(252, 165, 165, 0.35)',
  },
  deleteAccountButtonDisabled: {
    opacity: 0.6,
  },
  deleteAccountButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FCA5A5',
  },
  deleteAccountHint: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 17,
  },
  deleteDataFooter: {
    alignItems: 'center',
    marginTop: 18,
  },
  deleteDataLink: {
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  deleteDataLinkText: {
    fontSize: 12,
    color: '#FCA5A5',
    textDecorationLine: 'underline',
  },
  // Auth form styles
  authForm: {
    flex: 1,
    paddingTop: 20,
  },
  authTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  authSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 24,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  errorText: {
    flex: 1,
    color: '#E07575',
    fontSize: 14,
  },
  successBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  successText: {
    flex: 1,
    color: '#10B981',
    fontSize: 14,
  },
  input: {
    backgroundColor: '#1a2028',
    borderWidth: 1,
    borderColor: '#2a3038',
    borderRadius: 10,
    padding: 14,
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 12,
  },
  authButton: {
    backgroundColor: '#10B981',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  authButtonDisabled: {
    opacity: 0.7,
  },
  authButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#2a3038',
  },
  dividerText: {
    color: '#6B7280',
    paddingHorizontal: 16,
    fontSize: 14,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#4285F4',
    paddingVertical: 14,
    borderRadius: 10,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  appleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#000000',
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#333333',
  },
  appleButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  authLinks: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  authLink: {
    color: '#10B981',
    fontSize: 14,
  },
  // New profile settings styles
  sectionHint: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 2,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    paddingBottom: 12,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionHeaderNoPress: {
    padding: 16,
    paddingBottom: 8,
  },
  sectionContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  countBadge: {
    backgroundColor: '#10B981',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  countText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  handicapCard: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.2)',
  },
  handicapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  handicapLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#10B981',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  handicapValue: {
    fontSize: 48,
    fontWeight: '700',
    color: '#10B981',
    marginVertical: 6,
  },
  handicapStatus: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 4,
  },
  handicapDetails: {
    alignItems: 'center',
    gap: 6,
  },
  handicapDetail: {
    fontSize: 13,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  handicapChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
  },
  handicapChangeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  handicapDate: {
    fontSize: 12,
    color: '#6B7280',
  },
  fallbackBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(245, 158, 11, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  fallbackText: {
    fontSize: 11,
    color: '#F59E0B',
    fontWeight: '600',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  goalRow: {
    backgroundColor: '#202733',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#2a3038',
  },
  goalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  goalLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  goalCurrent: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  goalInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  goalInputLabel: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  goalInput: {
    flex: 1,
    backgroundColor: '#1a2028',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 14,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#2a3038',
  },
  goalProgressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  goalProgressTrack: {
    flex: 1,
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  goalProgressFill: {
    height: '100%',
    backgroundColor: '#3B82F6',
  },
  goalProgressFillDone: {
    backgroundColor: '#10B981',
  },
  goalProgressText: {
    fontSize: 12,
    color: '#9CA3AF',
    width: 44,
    textAlign: 'right',
  },
  goalNoDataText: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  statCard: {
    flex: 1,
    minWidth: '30%',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  statDetail: {
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'center',
  },
  viewStatsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
  },
  viewStatsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  preferenceItem: {
    marginBottom: 20,
  },
  preferenceLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#E5E7EB',
    marginBottom: 12,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 8,
    padding: 4,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  segmentButtonActive: {
    backgroundColor: '#10B981',
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#9CA3AF',
  },
  segmentTextActive: {
    color: '#FFFFFF',
  },
  preferenceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  preferenceValue: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  preferenceHint: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
  },
  homeCourseChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  homeCourseChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
  },
  homeCourseChipActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderColor: '#10B981',
  },
  homeCourseChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D1D5DB',
  },
  homeCourseChipTextActive: {
    color: '#10B981',
  },
  homeCourseClear: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  homeCourseClearText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  appInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  appName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  appVersion: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  linkList: {
    gap: 8,
  },
  linkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  linkText: {
    flex: 1,
    fontSize: 14,
    color: '#E5E7EB',
  },
  creditsText: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 16,
  },
  modeToggleContainer: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  modeToggleButton: {
    flex: 1,
    backgroundColor: '#2a3038',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2a3038',
  },
  modeToggleButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderColor: '#10B981',
  },
  modeToggleText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#9CA3AF',
    marginBottom: 4,
  },
  modeToggleTextActive: {
    color: '#10B981',
  },
  modeToggleSubtext: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#252d38',
  },
  formLabel: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  formInput: {
    flex: 1,
    maxWidth: 180,
    backgroundColor: '#252d38',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: '#FFFFFF',
  },
  prefsContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  presetContainer: {
    paddingBottom: 8,
  },
  sectionLabel: {
    fontSize: 11,
    color: '#6B7280',
    letterSpacing: 1,
    marginBottom: 8,
  },
  presetButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  presetButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
  },
  presetButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D1D5DB',
  },
  presetHelpText: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 8,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#252d38',
  },
  toggleLabel: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  dnaActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  dnaActionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dnaActionTextBlock: {
    gap: 2,
  },
  dnaActionText: {
    fontSize: 14,
    color: '#E5E7EB',
    fontWeight: '600',
  },
  dnaActionSubtext: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  markingBlock: {
    paddingTop: 10,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#252d38',
  },
  markingButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  markingButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
    minWidth: 92,
  },
  markingButtonActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderColor: '#10B981',
  },
  markingButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D1D5DB',
  },
  markingButtonTextActive: {
    color: '#10B981',
  },
  markingPreview: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
  },
  markingHint: {
    fontSize: 11,
    color: '#6B7280',
    marginTop: 8,
  },
  bagContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  clubCategory: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 12,
    marginBottom: 8,
  },
  clubRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  clubButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#252d38',
    borderWidth: 1,
    borderColor: '#3a4048',
  },
  clubButtonActive: {
    backgroundColor: '#10B981',
    borderColor: '#10B981',
  },
  clubButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  clubButtonTextActive: {
    color: '#FFFFFF',
  },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#10B981',
    paddingVertical: 14,
    borderRadius: 12,
    marginVertical: 16,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  statInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: '#252d38',
  },
  statInfoText: {
    fontSize: 14,
    color: '#D1D5DB',
    flex: 1,
  },
  statTrackingNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 16,
    padding: 12,
    backgroundColor: 'rgba(107, 114, 128, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
  },
  statTrackingNoteText: {
    flex: 1,
    fontSize: 12,
    color: '#9CA3AF',
    lineHeight: 16,
  },
  basicTrackingSummary: {
    padding: 12,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: '#374151',
  },
  basicTrackingText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#E5E7EB',
    marginBottom: 4,
  },
  basicTrackingHint: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  roundsSummaryCard: {
    backgroundColor: '#1a2028',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2a3038',
  },
  roundsSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  roundsSummaryTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#10B981',
    letterSpacing: 0.8,
  },
  roundsSummaryLine: {
    fontSize: 13,
    color: '#E5E7EB',
    marginBottom: 6,
  },
  roundsSummaryBestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  roundsSummaryStreakRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  roundsSummaryStreakText: {
    fontSize: 13,
    color: '#F59E0B',
    fontWeight: '600',
  },
  roundsSummaryEmptyText: {
    fontSize: 13,
    color: '#9CA3AF',
    marginBottom: 10,
  },
  roundsSummaryCta: {
    alignSelf: 'flex-start',
    backgroundColor: '#10B981',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  roundsSummaryCtaText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f1419',
  },
  subscriptionCard: {
    backgroundColor: '#1a2028',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2a3038',
  },
  subscriptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  subscriptionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#10B981',
    letterSpacing: 0.8,
  },
  subscriptionPlan: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  subscriptionStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  subscriptionStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  subscriptionStatusText: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  subscriptionRenewalText: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  subscriptionManageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  subscriptionManageText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#10B981',
  },
});
