import { StyleSheet } from 'react-native';
import { colors, spacing, typography, radius } from '../theme/tokens';

export const YARDAGE_COLUMN_GAP = 6;
export const YARDAGE_DIVIDER_WIDTH = 8;
export const YARDAGE_CELL_GAP = 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg.primary,
  },
  content: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  contentWithStickyBar: {
    padding: spacing.lg,
    paddingBottom: spacing.xxxl,
  },
  section: {
    backgroundColor: colors.bg.secondary,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.bg.tertiary,
  },
  ratingMissingCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.bg.tertiary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.brand.primaryBorder,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  ratingMissingTitle: {
    ...typography.labelMd,
    color: colors.text.primary,
  },
  ratingMissingSubtitle: {
    ...typography.bodySm,
    color: colors.text.secondary,
    marginTop: spacing.xs,
  },
  addRatingButton: {
    backgroundColor: colors.brand.primary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
  },
  addRatingButtonText: {
    ...typography.labelSm,
    color: colors.text.inverse,
  },
  sectionNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.bg.primary,
    borderWidth: 1,
    borderColor: colors.bg.tertiary,
  },
  sectionNavButtonDisabled: {
    opacity: 0.5,
  },
  sectionNavText: {
    ...typography.labelSm,
    color: colors.text.primary,
  },
  sectionNavTextDisabled: {
    color: colors.text.tertiary,
  },
  sectionTitle: {
    ...typography.headingSm,
    color: colors.text.primary,
    marginBottom: spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionEditHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  sectionHintText: {
    ...typography.labelSm,
    color: colors.text.secondary,
  },
  sectionSubtitle: {
    ...typography.labelSm,
    color: colors.text.secondary,
    marginBottom: spacing.sm,
  },
  sectionTitleAlt: {
    ...typography.labelSm,
    color: colors.text.secondary,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  photoArea: {
    aspectRatio: 4 / 3,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#1F2937',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#374151',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  placeholder: {
    alignItems: 'center',
    gap: 8,
  },
  placeholderText: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '600',
  },
  thumbnailContainer: {
    width: '100%',
    height: '100%',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  thumbnailDimmed: {
    opacity: 0.5,
  },
  scanningOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  photoActions: {
    gap: 12,
    marginBottom: 16,
  },
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#10B981',
    backgroundColor: 'transparent',
  },
  selectButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10B981',
  },
  cameraButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
    backgroundColor: 'transparent',
  },
  cameraButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#9CA3AF',
  },
  scanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#10B981',
  },
  scanButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  changeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
  },
  changeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  progressContainer: {
    marginBottom: 16,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#374151',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: 3,
  },
  progressText: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  stepsContainer: {
    marginTop: 8,
  },
  stepsDivider: {
    height: 1,
    backgroundColor: '#374151',
    marginBottom: 16,
  },
  stepsHeader: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 12,
  },
  scanErrorBox: {
    marginTop: 12,
    backgroundColor: '#111827',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
    padding: 12,
  },
  scanErrorTitle: {
    color: '#FCA5A5',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 6,
  },
  scanErrorHint: {
    color: '#E5E7EB',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  scanErrorBullet: {
    color: '#9CA3AF',
    fontSize: 12,
    marginBottom: 2,
  },
  scanErrorActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  scanErrorPrimary: {
    flex: 1,
    backgroundColor: '#10B981',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  scanErrorPrimaryText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  scanErrorSecondary: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#374151',
    paddingVertical: 10,
    alignItems: 'center',
  },
  scanErrorSecondaryText: {
    color: '#E5E7EB',
    fontSize: 12,
    fontWeight: '600',
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 10,
  },
  stepIcon: {
    width: 24,
    alignItems: 'center',
  },
  emptyCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#4B5563',
  },
  stepLabel: {
    fontSize: 15,
    color: '#9CA3AF',
    flex: 1,
  },
  stepLabelComplete: {
    color: '#FFFFFF',
  },
  stepDetail: {
    fontSize: 13,
    color: '#6B7280',
  },
  reviewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    marginTop: 16,
    borderRadius: 8,
    backgroundColor: '#1F2937',
  },
  reviewButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#10B981',
  },
  input: {
    backgroundColor: '#0F172A',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#E5E7EB',
    borderWidth: 1,
    borderColor: '#374151',
    marginBottom: 10,
  },
  inputTouchable: {
    justifyContent: 'center',
  },
  inputValueText: {
    color: '#E5E7EB',
    fontSize: 14,
    fontWeight: '600',
  },
  inputPlaceholderText: {
    color: '#6B7280',
    fontSize: 14,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  inputHalf: {
    flex: 1,
  },
  dateInput: {
    justifyContent: 'center',
  },
  dateInputText: {
    color: '#F9FAFB',
    fontSize: 14,
    fontWeight: '600',
  },
  datePlaceholderText: {
    color: '#6B7280',
    fontSize: 14,
  },
  courseSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  courseSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  courseSearchButtonText: {
    color: '#10B981',
    fontSize: 12,
    fontWeight: '600',
  },
  courseSearchHint: {
    color: '#6B7280',
    fontSize: 11,
    flex: 1,
    marginLeft: 8,
  },
  courseSuggestions: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#1F2937',
    marginBottom: 12,
  },
  courseSuggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(31, 41, 55, 0.6)',
  },
  courseSuggestionName: {
    color: '#E5E7EB',
    fontSize: 13,
    fontWeight: '600',
  },
  courseSuggestionMeta: {
    color: '#9CA3AF',
    fontSize: 11,
    marginTop: 2,
  },
  teeTabRow: {
    marginBottom: 12,
  },
  teeTab: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: '#374151',
    marginRight: 8,
  },
  teeTabActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: '#10B981',
  },
  teeTabText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  teeTabTextActive: {
    color: '#10B981',
  },
  teeTabAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.4)',
  },
  teeTabAddText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#10B981',
  },
  teeBoxFields: {
    paddingTop: 8,
  },
  removeTeeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  removeTeeButtonText: {
    fontSize: 12,
    color: '#F87171',
    fontWeight: '600',
  },
  playerHeader: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  firPar3HintText: {
    color: '#6B7280',
    fontSize: 11,
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  playerHeaderText: {
    color: '#9CA3AF',
    fontSize: 11,
    textAlign: 'center',
    flex: 0,
  },
  headerHoleCell: {
    width: 28,
    flex: 0,
  },
  headerScoreCell: {
    width: 44,
    flex: 0,
  },
  headerStatCell: {
    width: 44,
    flex: 0,
  },
  holeCell: {
    width: 28,
    textAlign: 'center',
  },
  scoreCell: {
    width: 44,
  },
  statCell: {
    width: 44,
  },
  playerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  playerRowFocused: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderRadius: 10,
    paddingVertical: 4,
  },
  namePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  namePickerButtonText: {
    color: '#10B981',
    fontSize: 13,
    fontWeight: '600',
  },
  nineToggle: {
    flexDirection: 'row',
    backgroundColor: '#1F2937',
    borderRadius: 8,
    padding: 4,
    marginBottom: 12,
  },
  nineButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  nineButtonActive: {
    backgroundColor: '#374151',
  },
  nineButtonText: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  nineButtonTextActive: {
    color: '#FFFFFF',
  },
  nineButtonDisabled: {
    opacity: 0.5,
  },
  nineButtonTextDisabled: {
    color: '#6B7280',
  },
  yardageHeaderRow: {
    flexDirection: 'row',
    marginBottom: 6,
    justifyContent: 'flex-start',
    gap: YARDAGE_CELL_GAP,
  },
  yardageColumns: {
    flexDirection: 'row',
    gap: YARDAGE_COLUMN_GAP,
  },
  yardageColumn: {
    flex: 1,
  },
  yardageDivider: {
    width: YARDAGE_DIVIDER_WIDTH,
  },
  yardageHeaderText: {
    color: '#9CA3AF',
    fontSize: 9,
    textAlign: 'center',
  },
  yardageHoleCell: {
    width: 16,
    textAlign: 'center',
  },
  yardageParCell: {
    width: 24,
  },
  yardageHcpCell: {
    width: 22,
  },
  yardageYardCell: {
    width: 52,
  },
  yardageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    justifyContent: 'flex-start',
    gap: YARDAGE_CELL_GAP,
  },
  yardageCell: {
    height: 32,
    borderRadius: 8,
    backgroundColor: '#1F2937',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 0,
  },
  yardageCellText: {
    color: '#E5E7EB',
    fontSize: 11,
    fontWeight: '600',
  },
  yardageHoleText: {
    color: '#E5E7EB',
    fontSize: 10,
    textAlign: 'center',
  },
  nineTotals: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: '#374151',
    marginTop: 8,
  },
  nineTotalsColumn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 6,
    borderTopWidth: 1,
    borderTopColor: '#374151',
    marginTop: 8,
  },
  nineTotalsLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  nineTotalsScore: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  nineTotalsToPar: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  nineTotalsPutts: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  focusedHoleBanner: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  focusedHoleText: {
    color: '#BFDBFE',
    fontSize: 12,
    fontWeight: '600',
  },
  advancedLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    fontWeight: '600',
    marginBottom: 6,
  },
  advancedValue: {
    fontSize: 13,
    color: '#E5E7EB',
    marginBottom: 12,
  },
  sectionSkeleton: {
    backgroundColor: '#1F2937',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#374151',
    gap: 12,
  },
  skeletonLine: {
    height: 14,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  skeletonLineShort: {
    height: 14,
    width: '60%',
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  keypadOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2, 6, 23, 0.7)',
    justifyContent: 'flex-end',
  },
  keypadBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  keypadContainer: {
    backgroundColor: '#111827',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  namePickerContainer: {
    backgroundColor: '#111827',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  namePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  namePickerTitle: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '600',
  },
  namePickerOption: {
    backgroundColor: '#1F2937',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  namePickerOptionText: {
    color: '#F9FAFB',
    fontSize: 15,
    fontWeight: '600',
  },
  namePickerOptionHint: {
    color: '#9CA3AF',
    fontSize: 12,
    marginTop: 4,
  },
  keypadHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  keypadTitle: {
    color: '#E5E7EB',
    fontSize: 16,
    fontWeight: '600',
  },
  keypadValueRow: {
    alignItems: 'center',
    marginBottom: 16,
  },
  keypadValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#10B981',
  },
  chipSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 16,
    textAlign: 'center',
  },
  chipRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  chip: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipSelected: {
    backgroundColor: '#10B981',
  },
  chipText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  chipTextSelected: {
    color: '#FFFFFF',
  },
  chipHint: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 6,
  },
  keypadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  keypadKey: {
    width: '30%',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#1F2937',
    alignItems: 'center',
  },
  keypadKeySecondary: {
    width: '30%',
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#0F172A',
    alignItems: 'center',
  },
  keypadKeyText: {
    color: '#E5E7EB',
    fontSize: 20,
    fontWeight: '600',
  },
  keypadFooterNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  keypadNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: '#1F2937',
  },
  keypadNavText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
  },
  keypadDone: {
    marginTop: 16,
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  keypadDoneText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  holeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  holeNumber: {
    color: '#E5E7EB',
    textAlign: 'center',
    width: 28,
  },
  holeInput: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 6,
    color: '#E5E7EB',
    borderWidth: 1,
    borderColor: '#374151',
    textAlign: 'center',
    marginHorizontal: 2,
  },
  cellEditable: {
    borderColor: '#475569',
  },
  cellEdited: {
    borderColor: colors.brand.primary,
  },
  cellEditedDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.brand.primary,
  },
  holeInputText: {
    color: '#E5E7EB',
    textAlign: 'center',
    fontSize: 14,
  },
  flagToggle: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#374151',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
  },
  flagToggleDisabled: {
    opacity: 0.4,
  },
  flagToggleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E5E7EB',
  },
  showAllStatsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#374151',
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  showAllStatsText: {
    ...typography.labelSm,
    color: colors.text.secondary,
  },
});

export type ScorecardImportStyles = typeof styles;
